### ISSUE TITLE
CLAMR fails to build on GCC<8

### ISSUE THREAD

**Issue by adegomme** [lanl/CLAMR#58]
The -mprefer-vector-width=x option seems to have been added only recently in GCC, so building with 7.4 is currently failing.

**Comment by brobey** [comment]
Took out the flag for now


Sent with BlackBerry Work
(www.blackberry.com)

**Comment by adegomme** [comment]
Hi,
due to the release of gcc 7.5, this issue is back. The tests in cmake/Modules/FindVector.cmake  based on 7.4.0 should be bumped to 7.5.0 or use "NOT VERSION_LESS 8.0" instead (7.5 should be the last 7.x version anyway... until the next one?).
