### ISSUE TITLE
Updating from Python 2 to Python 3

### ISSUE THREAD

**Issue by maycontainjane** [lanl/CLAMR#70]
Our codebase will soon no longer support Python 2. We have CLAMR within our tests and have noticed that there is some code that is explicitly Python 2, including the `generate_image.py` script and a call in `clamr_plot.py`:

https://github.com/lanl/CLAMR/blob/07ae359d9e73f1d598621b2517ae6c42826f9c37/tests/hlopenmp_paper/clamr_plot.py#L15

We were curious if there is any plan to update CLAMR, or if the python2->python3 updates from our side may be desirable in a PR to this repo.

**Comment by brobey** [comment]
I can update it. I appreciate the heads up and which routines.

From: Jane ***@***.***>
Reply-To: lanl/CLAMR ***@***.***>
Date: Friday, April 30, 2021 at 3:35 PM
To: lanl/CLAMR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [lanl/CLAMR] Updating from Python 2 to Python 3 (#70)


Our codebase will soon no longer support Python 2. We have CLAMR within our tests and have noticed that there is some code that is explicitly Python 2, including the generate_image.py script and a call in clamr_plot.py:

https://github.com/lanl/CLAMR/blob/07ae359d9e73f1d598621b2517ae6c42826f9c37/tests/hlopenmp_paper/clamr_plot.py#L15

We were curious if there is any plan to update CLAMR, or if the python2->python3 updates from our side may be desirable in a PR to this repo.

**Comment by brobey** [comment]
The python scripts that were still python 2.7 are now updated to python 3.0.
